### ISSUE TITLE
No podspec found for `uni_links_nfc_support`

### ISSUE THREAD

**Issue by SlavisDEV** [doch2/uni_links_nfc_support#1]
I am getting this error while I am trying to build the iOS app. 
Does anyone have any idea?

`No podspec found for uni_links_nfc_support in .symlinks/plugins/ini_links_nfc_support/ios`

Thanks!

**Comment by doch2** [comment]
Would you like to run the `pod install` or `pod update` commands in the ios folder of the project?

**Comment by SlavisDEV** [comment]
I tried and nothing has changed. 
If I switch `uni_links_nfc_support` to the standard `uni_links`, everything works.

**Comment by doch2** [comment]
Would you like to create a new project and add the `uni_links_nfc_support` package to Dependency there? Please let me know if the same error occurs.

**Comment by doch2** [comment]
Resolved by #2 PR.
